### ISSUE TITLE
please add SCSS version

### ISSUE THREAD

**Issue by colthreepv** [adjohnson916/bootstrap-grid-ms#1]
There's really need to make order with all those bootstrap 3 ms gists

Would be cool if this project mantained LESS, SASS and SCSS versions with the same codebase, contributors can be added to review the different languages.

At least this is installable via bower/npm and that's a big plus

**Comment by AndersDJohnson** [comment]
@colthreepv Thanks for the suggestion. The source is in LESS only currently (https://github.com/adjohnson916/bootstrap-grid-ms/blob/master/less/bootstrap-grid-ms.less). I believe SASS can import SCSS and vice versa, so wouldn't only one of those be needed? Would it work for you now to just import the compiled CSS into your SASS or SCSS files? I don't know if SASS/SCSS supports that - you may have to rename the `.css` to `.scss` then import that. If it works, I could consider providing an already renamed `.scss` file in the Bower dist.

**Comment by AndersDJohnson** [comment]
@colthreepv See PR #3 by @cjke which I've merged and released to Bower as `v0.1.1`.
