### ISSUE TITLE
change display: block to display: table-cell?

### ISSUE THREAD

**Issue by pinkynrg** [adjohnson916/bootstrap-grid-ms#11]
I'm not good at styling at all. But isn't this a fix that makes sense?

```
// Misc. class adjustments for col-ms
@media (min-width: $screen-ms) and (max-width: $screen-ms-max) {
    .hidden-xs {
        display: table-cell !important; // now instead of table-cell is block
    }
}
```

I was getting my td screwed up when applying hidden-xs and hidden-ms at the same time.

Thanks,

**Comment by AndersDJohnson** [comment]
@pinkynrg I'm not sure you're using it in a typical way - not sure `hidden-*` classes are meant to be used on `td` elements. Instead, can you try wrapping the contents of your `td` in a `div`, then put your `hidden-*` class(es) on that?
