### ISSUE TITLE
Package.json postinstall

### ISSUE THREAD

**Issue by rawrmonstar** [adjohnson916/bootstrap-grid-ms#9]
Hi!

I was wondering what the purpose of the [postinstall script](https://github.com/adjohnson916/bootstrap-grid-ms/blob/66f10a7225a50bc9e716b80387da677f62bac94e/package.json#L8) in package.json was. It seems to me that someone wanting to use bower would use it to install this package rather than npm.

As it is, `npm install bootstrap-grid-ms --save` fails if you don't already have bower installed because it is listed as a devDependencies and is not pulled in.  So I guess my question is, is the postinstall script really necessary? I know it pulls in the bower dependencies i.e., bootstrap, but if you are going to use npm for the install, shouldn't bootstrap be listed as a npm dependency instead? Anyway, if bower is necessary and the postinstall needs to stay, then bower should probably should be listed as a regular dependencies instead of a devDependency in package.json so that it makes sure it is installed.

What do you think?

**Comment by AndersDJohnson** [comment]
@rawrmonstar You're right, thanks. The npm `postinstall` was just a convenient place to install Bower dependencies needed for the build check I have running on Travis CI, but I was able to switch that to a `before_script` in the `.travis.yml` config. Then npm users don't need Bower installed, and don't need to do an `npm install --dev`. See 9bc496010b267a2177d8ee65f39b6d7960a067af.

**Comment by AndersDJohnson** [comment]
@rawrmonstar Released to npm and Bower as `1.0.1`.
